
import { FirebaseStorage } from "./storage";

async function seed() {
    console.log("🌱 Starting Firestore seed...");

    if (!process.env.FIREBASE_SERVICE_ACCOUNT) {
        console.error("❌ FIREBASE_SERVICE_ACCOUNT env var missing!");
        process.exit(1);
    }

    const storage = new FirebaseStorage();

    // EVENTS DATA
    const events = [
        // MECH
        {
            id: "evt-mech-001",
            title: "Tech Olympics",
            type: "tech",
            department: "MECH",
            shortDescription: "Mechanical engineering challenges and contests.",
            fullDescription: "A series of hands-on technical challenges designed for mechanical engineering enthusiasts.",
            date: "23-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Standard safety gear required", "Participants must bring college ID"],
            tags: ["mechanical", "competition"],
            image: "/assets/events/tech-olympics.png",
            venue: "Basket ball court",
            contactNo: "9966139994",
            facultyCoordinator: "Dr. R. Bhargavi & Mr. G. Jaya Raju"
        },
        {
            id: "evt-mech-002",
            title: "Go Karting",
            type: "tech",
            department: "MECH",
            shortDescription: "Race your way to victory.",
            fullDescription: "Experience the thrill of high-speed racing in our custom-designed karting track.",
            date: "23-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Helmets mandatory", "Strict adherence to track signals"],
            tags: ["mechanical", "competition"],
            image: "/assets/events/go-karting.png",
            venue: "Near 'W' block",
            contactNo: "9490501085",
            facultyCoordinator: "Dr. V. Ajay Kumar & Mr. B. Nani"
        },
        {
            id: "evt-mech-quiz",
            title: "Technical Quiz",
            type: "tech",
            department: "MECH",
            shortDescription: "Mechanical technical quiz.",
            fullDescription: "Test your knowledge of the latest developments in mechanical engineering.",
            date: "23-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Multiple rounds", "Rapid fire final"],
            tags: ["quiz", "mechanical"],
            image: "/assets/events/technical-quiz.png",
            venue: "R 307B",
            contactNo: "9949221277",
            facultyCoordinator: "Dr. B. Kiran Babu & Mr. N. Ranjith Kumar"
        },
        {
            id: "evt-mech-exh",
            title: "Project Exhibition",
            type: "tech",
            department: "MECH",
            shortDescription: "Showcase your innovations.",
            fullDescription: "An opportunity for students to demonstrate their mechanical projects and innovations.",
            date: "23-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Open only to final-year students.", "Projects must be technical in nature."],
            tags: ["innovation", "mechanical"],
            image: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&q=80",
            venue: "R 307A",
            contactNo: "9912866226",
            facultyCoordinator: "Mrs. K. Vidya"
        },
        {
            id: "evt-mech-poster",
            title: "Poster Presentation",
            type: "tech",
            department: "MECH",
            shortDescription: "Visual presentation of research ideas.",
            fullDescription: "Design and present a poster summarizing a mechanical technical research topic.",
            date: "23-01-2026",
            startTime: "10:00",
            endTime: "15:00",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Posters must be technical-topic based.", "Posters should be colored and clearly explained."],
            tags: ["research", "mechanical"],
            image: "/assets/events/poster-presentation.png",
            venue: "R 307A",
            contactNo: "7893602287",
            facultyCoordinator: "Mr. Nawab Abdul"
        },
        {
            id: "evt-mech-paper",
            title: "Paper Presentation",
            type: "tech",
            department: "MECH",
            shortDescription: "Present your technical papers.",
            fullDescription: "Submit and present mechanical research papers to a panel of expert judges.",
            date: "23-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Topics must be technical.", "A maximum of 10 slides is sufficient."],
            tags: ["mechanical", "competition"],
            image: "/assets/events/paper_presentation.png",
            venue: "R 306B",
            contactNo: "7901533324",
            facultyCoordinator: "Dr. P. Danaiah"
        },
        // CSE, AIML & DS
        {
            id: "evt-cse-001",
            title: "Tech Talks",
            type: "tech",
            department: "CSE/AI",
            shortDescription: "Insightful sessions on emerging technologies.",
            fullDescription: "Expert talks on AI, Machine Learning, and the future of Computing.",
            date: "23-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Participants must present on a relevant technical topic.", "Clarity, confidence, and content quality will be evaluated."],
            tags: ["AI", "ML", "Computer Science"],
            image: "/assets/events/tech_talks.png",
            venue: "R310",
            contactNo: "6305806663",
            facultyCoordinator: "Dr. VGNS Prasad and R. Sriram"
        },
        {
            id: "evt-cse-002",
            title: "Cryptic Crosswords",
            type: "tech",
            department: "CSE/AI",
            shortDescription: "Solve the code, win the game.",
            fullDescription: "A tech-themed crossword competition to test your vocabulary and knowledge.",
            date: "23-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["No mobile phones during the contest"],
            tags: ["puzzles", "logic"],
            image: "https://images.unsplash.com/photo-1614850523296-d8c1af93d400?w=800&q=80",
            venue: "R201",
            contactNo: "9573752230",
            facultyCoordinator: "P. Bhagyasri and P. Usha sri"
        },
        {
            id: "evt-cse-003",
            title: "Prompt AI",
            type: "tech",
            department: "CSE/AI",
            shortDescription: "Master the art of prompt engineering.",
            fullDescription: "Competitions focused on generating the best outputs from AI models using creative prompts.",
            date: "23-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Use of specific AI models only", "Ethical guidelines apply"],
            tags: ["AI", "Prompting"],
            image: "/assets/events/prompt-ai.png",
            venue: "CP LAB 2",
            contactNo: "6281016866",
            facultyCoordinator: "B. Sowmya"
        },
        {
            id: "evt-cse-004",
            title: "Rapid Coders",
            type: "tech",
            department: "CSE/AI",
            shortDescription: "Speed coding challenge.",
            fullDescription: "Solve programming problems as fast as you can in this high-intensity coding sprint.",
            date: "23-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Standard competitive programming rules apply"],
            tags: ["coding", "programming"],
            image: "https://images.unsplash.com/photo-1516259762381-22954d7d3ad2?w=800&q=80",
            facultyCoordinator: "T N Mounika and K Surya"
        },
        {
            id: "evt-cse-005",
            title: "Beat The Clock",
            type: "tech",
            department: "CSE/AI",
            shortDescription: "Time-bound technical tasks.",
            fullDescription: "A series of quick-fire technical tasks where you race against the timer.",
            date: "23-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Completion within time is key"],
            tags: ["stamina", "logic"],
            image: "https://images.unsplash.com/photo-1501139083538-0139583c060f?w=800&q=80",
            venue: "R308",
            contactNo: "9948699901",
            facultyCoordinator: "S Gogulapriya and M Chanti Babu"
        },
        {
            id: "evt-cse-quiz",
            title: "Technical Quiz",
            type: "tech",
            department: "CSE/AI",
            shortDescription: "Computer science quiz.",
            fullDescription: "Test your knowledge of the latest developments in CSE & AI.",
            date: "23-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Multiple rounds", "Rapid fire final"],
            tags: ["quiz", "CSE", "AI"],
            image: "/assets/events/technical-quiz.png",
            facultyCoordinator: "Ch Phani and K Rajasekhar"
        },
        {
            id: "evt-cse-exh",
            title: "Project Exhibition",
            type: "tech",
            department: "CSE/AI",
            shortDescription: "Showcase your prototypes.",
            fullDescription: "An opportunity for students to demonstrate their CSE/AI projects and innovations.",
            date: "23-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Open only to final-year students.", "Projects must be technical in nature."],
            tags: ["innovation", "CSE", "AI"],
            image: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&q=80",
            facultyCoordinator: "K Bhavani and M Chaitanya"
        },
        {
            id: "evt-cse-poster",
            title: "Poster Presentation",
            type: "tech",
            department: "CSE/AI",
            shortDescription: "Visual presentation of research ideas.",
            fullDescription: "Design and present a poster summarizing a CSE/AI research topic.",
            date: "23-01-2026",
            startTime: "10:00",
            endTime: "15:00",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Posters must be technical-topic based.", "Posters should be colored and clearly explained."],
            tags: ["research", "CSE", "AI"],
            image: "/assets/events/poster-presentation.png",
            facultyCoordinator: "S Mounika and P Pranitha"
        },
        {
            id: "evt-cse-paper",
            title: "Paper Presentation",
            type: "tech",
            department: "CSE/AI",
            shortDescription: "Present your technical papers.",
            fullDescription: "Submit and present CSE/AI research papers to a panel of expert judges.",
            date: "23-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Topics must be technical.", "A maximum of 10 slides is sufficient."],
            tags: ["academic", "CSE", "AI"],
            image: "/assets/events/paper_presentation.png",
            facultyCoordinator: "Dr B Asha Latha and K Jyothi"
        },
        // IT
        {
            id: "evt-it-001",
            title: "Hackathon",
            type: "tech",
            department: "IT",
            shortDescription: "Build a solution in one day.",
            fullDescription: "Intensive design and development event to solve real-world problems.",
            date: "23-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Teams must present a productive and implementable idea.", "Innovation and problem-solving approach are mandatory."],
            tags: ["hacking", "development"],
            image: "https://images.unsplash.com/photo-1516259762381-22954d7d3ad2?w=800&q=80",
            venue: "U406",
            contactNo: "77027 20850",
            facultyCoordinator: "B. Sirisha"
        },
        {
            id: "evt-it-002",
            title: "Innovation Ideas",
            type: "tech",
            department: "IT",
            shortDescription: "Pitch your startup concepts.",
            fullDescription: "Pitch decks and business plans for new tech-driven business ideas.",
            date: "23-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Limit to 5 min pitch"],
            tags: ["startup", "ideas"],
            image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80",
            venue: "U311",
            contactNo: "63015 52836",
            facultyCoordinator: "CH. Madhu Babu"
        },
        {
            id: "evt-it-quiz",
            title: "Technical Quiz",
            type: "tech",
            department: "IT",
            shortDescription: "Information technology quiz.",
            fullDescription: "Test your knowledge of the latest developments in IT.",
            date: "23-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Multiple rounds", "Rapid fire final"],
            tags: ["quiz", "IT"],
            image: "/assets/events/technical-quiz.png"
        },
        {
            id: "evt-it-exh",
            title: "Project Exhibition",
            type: "tech",
            department: "IT",
            shortDescription: "Showcase your prototypes.",
            fullDescription: "An opportunity for students to demonstrate their IT projects and innovations.",
            date: "23-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Open only to final-year students.", "Projects must be technical in nature."],
            tags: ["innovation", "IT"],
            image: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&q=80"
        },
        {
            id: "evt-it-poster",
            title: "Poster Presentation",
            type: "tech",
            department: "IT",
            shortDescription: "Visual presentation of research ideas.",
            fullDescription: "Design and present a poster summarizing an IT research topic.",
            date: "23-01-2026",
            startTime: "10:00",
            endTime: "15:00",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Posters must be technical-topic based.", "Posters should be colored and clearly explained."],
            tags: ["research", "IT"],
            image: "/assets/events/poster-presentation.png",
            venue: "U405",
            contactNo: "9703418339",
            facultyCoordinator: "B. Trivikrama Rao"
        },
        {
            id: "evt-it-paper",
            title: "Paper Presentation",
            type: "tech",
            department: "IT",
            shortDescription: "Present your technical papers.",
            fullDescription: "Submit and present IT research papers to a panel of expert judges.",
            date: "23-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Topics must be technical.", "A maximum of 10 slides is sufficient."],
            tags: ["academic", "IT"],
            image: "/assets/events/paper_presentation.png",
            venue: "U403",
            contactNo: "99636 67936",
            facultyCoordinator: "M. Rajesh"
        },
        // ECE
        {
            id: "evt-ece-001",
            title: "Circuitrix",
            type: "tech",
            department: "ECE",
            shortDescription: "Test your circuit debugging skills.",
            fullDescription: "A hands-on challenge to debug and complete missing parts of a complex circuit board.",
            date: "23-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Safety first", "Components provided"],
            tags: ["electronics", "hardware"],
            image: "/assets/events/circuitrix.png",
            contactNo: "9703370227",
            facultyCoordinator: "Mrs. U. Nalini"
        },
        {
            id: "evt-ece-002",
            title: "Stress Burst",
            type: "tech",
            department: "ECE",
            shortDescription: "Fast-paced technical trivia.",
            fullDescription: "Rapid response technical challenges specifically for ECE concepts.",
            date: "23-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Speed and accuracy"],
            tags: ["quiz", "fast-paced"],
            image: "/assets/events/stress_burst.png",
            contactNo: "8801427804",
            facultyCoordinator: "Mr. G. Rajesh Babu"
        },
        {
            id: "evt-ece-003",
            title: "Mystery Busters",
            type: "tech",
            department: "ECE",
            shortDescription: "Sherlock-style technical hunt.",
            fullDescription: "Solve clues hidden in circuits and component data sheets to reach the goal.",
            date: "23-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Mobile tracking mandatory"],
            tags: ["treasure-hunt", "clues"],
            image: "https://images.unsplash.com/photo-1558449028-b53a39d100fc?w=800&q=80",
            contactNo: "7396652874",
            facultyCoordinator: "Mr. P. Venkanna"
        },
        {
            id: "evt-ece-004",
            title: "Techno Parady",
            type: "tech",
            department: "ECE",
            shortDescription: "Creative tech reimagining.",
            fullDescription: "A contest involving re-designing or paradying everyday tech objects for comical or alternate uses.",
            date: "23-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Humor allowed but respectful"],
            tags: ["humor", "creative"],
            image: "/assets/events/techno-parady.png",
            contactNo: "9440110662",
            facultyCoordinator: "Mr. K. N. V. Prasad"
        },
        {
            id: "evt-ece-quiz",
            title: "Technical Quiz",
            type: "tech",
            department: "ECE",
            shortDescription: "Electronics quiz.",
            fullDescription: "Test your knowledge of the latest developments in ECE.",
            date: "23-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Multiple rounds", "Rapid fire final"],
            tags: ["quiz", "ECE"],
            image: "/assets/events/technical-quiz.png",
            contactNo: "7702 191 922",
            facultyCoordinator: "Dr. M. V. Srikanth"
        },
        {
            id: "evt-ece-exh",
            title: "Project Exhibition",
            type: "tech",
            department: "ECE",
            shortDescription: "Showcase your innovations.",
            fullDescription: "An opportunity for students to demonstrate their ECE projects and innovations.",
            date: "23-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Open only to final-year students.", "Projects must be technical in nature."],
            tags: ["innovation", "ECE"],
            image: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&q=80",
            contactNo: "98855 71089",
            facultyCoordinator: "Mrs. K. Nitya"
        },
        {
            id: "evt-ece-poster",
            title: "Poster Presentation",
            type: "tech",
            department: "ECE",
            shortDescription: "Visual presentation of research ideas.",
            fullDescription: "Design and present a poster summarizing an ECE research topic.",
            date: "23-01-2026",
            startTime: "10:00",
            endTime: "15:00",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Posters must be technical-topic based.", "Posters should be colored and clearly explained."],
            tags: ["research", "ECE"],
            image: "/assets/events/poster-presentation.png",
            contactNo: "98855 09518",
            facultyCoordinator: "Mr. D. Srinivasulu"
        },
        {
            id: "evt-ece-paper",
            title: "Paper Presentation",
            type: "tech",
            department: "ECE",
            shortDescription: "Present your technical papers.",
            fullDescription: "Submit and present ECE research papers to a panel of expert judges.",
            date: "23-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Topics must be technical.", "A maximum of 10 slides is sufficient."],
            tags: ["academic", "ECE"],
            image: "/assets/events/paper_presentation.png",
            contactNo: "98668 47510",
            facultyCoordinator: "Dr. E. Naga Venkata"
        },
        // EEE
        {
            id: "evt-eee-001",
            title: "Paper Presentation",
            type: "tech",
            department: "EEE",
            shortDescription: "Present your technical papers.",
            fullDescription: "Submit and present EEE research papers to a panel of expert judges.",
            date: "23-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Topics must be technical.", "A maximum of 10 slides is sufficient."],
            tags: ["academic", "EEE"],
            image: "/assets/events/paper_presentation.png"
        },
        // DIPLOMA
        {
            id: "evt-dip-quiz",
            title: "Technical Quiz",
            type: "tech",
            department: "DIPLOMA",
            shortDescription: "Technical quiz for diploma students.",
            fullDescription: "Test your technical knowledge in this diploma-focused quiz competition.",
            date: "23-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Multiple rounds", "Rapid fire final"],
            tags: ["quiz", "DIPLOMA"],
            image: "/assets/events/technical-quiz.png"
        },
        {
            id: "evt-dip-exh",
            title: "Project Exhibition",
            type: "tech",
            department: "DIPLOMA",
            shortDescription: "Showcase your innovatve prototypes.",
            fullDescription: "An opportunity for diploma students to demonstrate their innovative projects.",
            date: "23-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Open only to final-year students.", "Projects must be technical in nature."],
            tags: ["innovation", "DIPLOMA"],
            image: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&q=80"
        },
        {
            id: "evt-dip-poster",
            title: "Poster Presentation",
            type: "tech",
            department: "DIPLOMA",
            shortDescription: "Visual presentation of research ideas.",
            fullDescription: "Design and present a poster summarizing a technical research topic.",
            date: "23-01-2026",
            startTime: "10:00",
            endTime: "15:00",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Posters must be technical-topic based.", "Posters should be colored and clearly explained."],
            tags: ["research", "DIPLOMA"],
            image: "/assets/events/poster-presentation.png"
        },
        {
            id: "evt-dip-paper",
            title: "Paper Presentation",
            type: "tech",
            department: "DIPLOMA",
            shortDescription: "Present your technical papers.",
            fullDescription: "Submit and present research papers to a panel of expert judges.",
            date: "23-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Topics must be technical.", "A maximum of 10 slides is sufficient."],
            tags: ["academic", "DIPLOMA"],
            image: "/assets/events/paper_presentation.png"
        },
        // Cultural Events (24-01-2026)
        {
            id: "evt-cul-001",
            title: "Telugu Ammai",
            type: "cultural",
            department: "CULTURAL",
            shortDescription: "Traditional beauty and talent contest.",
            fullDescription: "Celebrating Telugu aesthetic, oratory, and cultural knowledge.",
            date: "24-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Only female participants are allowed.", "Participants must wear traditional Telugu attire."],
            tags: ["tradition", "talent"],
            image: "/assets/events/telugu-ammai.png",
            venue: "U-Block Seminar Hall",
            contactNo: "9182616668",
            facultyCoordinator: "Mrs K. Nitya",
            studentCoordinator: "Advisory Committee: Dr. Ch. Santhi Rani, Dr. KPNV. Satya Sree, Dr. R. Bhargavi, M. Deepthi, K. Ratna Sree"
        },
        {
            id: "evt-cul-002",
            title: "Best Dancer",
            type: "cultural",
            department: "CULTURAL",
            shortDescription: "Dance solo competition.",
            fullDescription: "Street, classical, or contemporary—show us your best moves.",
            date: "24-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Participants may perform to any movie or non-movie songs.", "Exception: Songs related to top hero families are not allowed."],
            tags: ["dance", "performance"],
            image: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&q=80",
            venue: "R301",
            contactNo: "9550419419",
            facultyCoordinator: "Mr K. Koteshwara Kishore"
        },
        {
            id: "evt-cul-003",
            title: "Best Singer",
            type: "cultural",
            department: "CULTURAL",
            shortDescription: "Vocal and karaoke challenge.",
            fullDescription: "Solo singing competition across various genres.",
            date: "24-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Any language is permitted unless specified otherwise by the judges."],
            tags: ["music", "voice"],
            image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&q=80",
            venue: "R309",
            contactNo: "9347226667",
            facultyCoordinator: "Mr. Ch Phani Kumar"
        },
        {
            id: "evt-cul-004",
            title: "Best Reels",
            type: "cultural",
            department: "CULTURAL",
            shortDescription: "Content creation contest.",
            fullDescription: "Submit short reels capturing the essence of the fest.",
            date: "24-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Participants must submit 2 reels.", "Each reel must be less than 30 seconds.", "The participant must be visibly present in the reel."],
            tags: ["social-media", "creative"],
            image: "https://images.unsplash.com/photo-1518467166778-b88f373ffec7?w=800&q=80",
            venue: "R108",
            contactNo: "9032832857",
            facultyCoordinator: "Mr. D. Hari Chanrda Prasad Babu Naik"
        },
        {
            id: "evt-cul-005",
            title: "Spot Photography",
            type: "cultural",
            department: "CULTURAL",
            shortDescription: "Capture moments on the fly.",
            fullDescription: "Photograph a given theme within the campus on the day of the fest.",
            date: "24-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Participants must bring their own camera.", "Photography must be done only within the campus.", "Photos must be captured within the given time limit."],
            tags: ["photography", "art"],
            image: "https://images.unsplash.com/photo-1495745966610-2a67f2297e5e?w=800&q=80",
            venue: "R404",
            contactNo: "7093325903",
            facultyCoordinator: "Mr E. Rama Krishna Reddy"
        },
        {
            id: "evt-cul-006",
            title: "Science Fair",
            type: "cultural",
            department: "CULTURAL",
            shortDescription: "Exhibiting the wonders of science.",
            fullDescription: "Demonstrate scientific principles through creative experiments.",
            date: "24-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Participants must bring working models.", "Models should be related to General Science or Engineering concepts."],
            tags: ["science", "learning"],
            image: "/assets/events/science_fair.png",
            venue: "R105",
            contactNo: "8125813894",
            facultyCoordinator: "Mr D. Sahitya Devi"
        },
        {
            id: "evt-cul-007",
            title: "Flower Arrangement",
            type: "cultural",
            department: "CULTURAL",
            shortDescription: "Art with petals.",
            fullDescription: "Creating beautiful floral displays within a time limit.",
            date: "24-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Flowers must be arranged on paper, cloth, or wooden base.", "Arrangement should be creative and aesthetically appealing.", "Final work must be submitted within the given time."],
            tags: ["art", "natural"],
            image: "https://images.unsplash.com/photo-1526047932273-341f2a7631f9?w=800&q=80",
            venue: "R103",
            contactNo: "8121630984",
            facultyCoordinator: "Ms. G. Sree Manogna"
        },
        {
            id: "evt-cul-008",
            title: "Talkathon",
            type: "cultural",
            department: "CULTURAL",
            shortDescription: "Declamations and speeches.",
            fullDescription: "Speaking competition focused on persuasive and informative topics.",
            date: "24-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["The event consists of 3 stages.", "Participants must speak only in English throughout the event."],
            tags: ["speaking", "debate"],
            image: "/assets/events/talkathon.png",
            venue: "R104",
            contactNo: "7995487415",
            facultyCoordinator: "Mr R Simhachalam"
        },
        {
            id: "evt-cul-009",
            title: "Painting/Art",
            type: "cultural",
            department: "CULTURAL",
            shortDescription: "Canvas and colors.",
            fullDescription: "On-the-spot painting based on a provided mysterious prompt.",
            date: "24-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["The management will provide only white drawing sheets.", "Participants must bring their own stationery and colors."],
            tags: ["painting", "creative"],
            image: "/assets/events/painting_art.png",
            venue: "Drawing Hall U412",
            contactNo: "9963132131",
            facultyCoordinator: "Mrs. S. Sri Laxmi"
        },
        {
            id: "evt-cul-010",
            title: "Literary Maze",
            type: "cultural",
            department: "CULTURAL",
            shortDescription: "Puzzles and literature.",
            fullDescription: "Word-based puzzles, scavenger hunts involving famous book quotes and authors.",
            date: "24-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Fastest solvers win"],
            tags: ["literature", "maze"],
            image: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=800&q=80",
            venue: "R102",
            contactNo: "9014938372",
            facultyCoordinator: "Mrs. R. Sarojini Devi"
        },
        {
            id: "evt-cul-011",
            title: "Mr. Perfect",
            type: "cultural",
            department: "CULTURAL",
            shortDescription: "Personality and talent contest for boys.",
            fullDescription: "Judged on fitness, general knowledge, and artistic talent.",
            date: "24-01-2026",
            startTime: "09:40 AM",
            endTime: "04:00 PM",
            teamSize: 1,
            registrationFee: 100,
            prize: "Cash Prize & Certificates",
            rules: ["Participants may dance, act, or perform a walk.", "The performance should clearly showcase individual talent."],
            tags: ["personality", "talent"],
            image: "/assets/events/mr_perfect.png",
            venue: "R-Block Seminar Hall",
            contactNo: "7396652874 & 9666969796",
            facultyCoordinator: "Mr. P. Venkanna & Mr. V. Mahesh"
        }
    ];

    // STALLS DATA
    const stalls = [
        {
            id: "stall-001",
            name: "Retro Bites — Food Court",
            type: "food",
            description: "Pixel-perfect snacks and neon-colored drinks. The main food hub of the festival.",
            owner: "Gourmet Pixels",
            booth: "F1-F5",
            location: "main-grounds",
            items: ["Glitch Burger", "Neon Soda", "8-bit Fries", "Cyber Cake"],
            priceRange: "₹50 - ₹250",
            openingHours: [
                { day: "2026-01-23", open: "10:00", close: "22:00" },
                { day: "2026-01-24", open: "10:00", close: "22:00" }
            ],
            contact: { phone: "+91-90000-11111", email: "food@usharama.edu" },
            image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&q=80"
        },
        {
            id: "stall-002",
            name: "VR Experience Zone",
            type: "gaming",
            description: "Immerse yourself in virtual worlds with the latest VR tech.",
            owner: "Virtual Reality India",
            booth: "G1",
            location: "gaming-hut",
            items: ["VR Quest", "Haptic Experience", "Metaverse Tour"],
            priceRange: "₹100/session",
            openingHours: [
                { day: "2026-01-23", open: "10:00", close: "18:00" },
                { day: "2026-01-24", open: "10:00", close: "18:00" }
            ],
            contact: { phone: "+91-90000-22222", email: "vr@gmail.com" },
            image: "https://images.unsplash.com/photo-1478416272538-5f7e51dc5400?w=800&q=80"
        },
        {
            id: "stall-003",
            name: "Custom PC Builders",
            type: "merchandise",
            description: "Get custom-built high-performance PC parts and expert advice.",
            owner: "Rig Master",
            booth: "M1-M3",
            location: "tech-lab",
            items: ["Custom Keyboards", "GPU Cooling Kits", "RGB Accessories"],
            priceRange: "Custom",
            openingHours: [
                { day: "2026-01-23", open: "09:00", close: "17:00" },
                { day: "2026-01-24", open: "09:00", close: "17:00" }
            ],
            contact: { phone: "+91-90000-33333", email: "rigmaster@gmail.com" },
            image: "https://images.unsplash.com/photo-1587202372775-e0631921a418?w=800&q=80"
        },
        {
            id: "stall-004",
            name: "The Tech Thrift Store",
            type: "merchandise",
            description: "Second-hand gadgets, rare parts, and tech souvenirs at great prices.",
            owner: "Tech Recycle",
            booth: "T1",
            location: "open-ground",
            items: ["Rare Cables", "Old Consoles", "Tech Tees"],
            priceRange: "₹20 - ₹2000",
            openingHours: [
                { day: "2026-01-23", open: "09:00", close: "19:00" },
                { day: "2026-01-24", open: "09:00", close: "19:00" }
            ],
            contact: { phone: "+91-90000-44444", email: "thrift@gmail.com" },
            image: "https://images.unsplash.com/photo-1533038590840-1cde6e668a91?w=800&q=80"
        }
    ];

    console.log(`Deleting existing events...`);
    await storage.clearEvents();
    console.log(`Seeding ${events.length} events...`);
    for (const event of events) {
        await storage.createEvent(event);
        console.log(`- Created event: ${event.title}`);
    }

    console.log(`Deleting existing stalls...`);
    await storage.clearStalls();
    console.log(`Seeding ${stalls.length} stalls...`);
    for (const stall of stalls) {
        await storage.createStall(stall);
        console.log(`- Created stall: ${stall.name}`);
    }

    console.log("✅ Seed completed successfully!");
    process.exit(0);
}

seed().catch(err => {
    console.error("❌ Seed failed:", err);
    process.exit(1);
});
